version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - 3000:3000
    restart: unless-stopped
  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - 3001:3000
    restart: unless-stopped
